import Head from "next/head";
import React from "react";
import logo from "../../assests/lg.jpeg";
export default function HeadComp() {
	return (
		<Head>
			<title>Surya Prakash Silk Mills</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/sew.png" />
		</Head>
	);
}
